apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jevlet-controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["jevlet.io"]
    resources: ["jevpolicies", "jevincidents"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["jevlet.io"]
    resources: ["jevpolicies/status", "jevincidents/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jevlet-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jevlet-controller
subjects:
  - kind: ServiceAccount
    name: jevlet-controller
    namespace: jevlet-system
